apiVersion: v1
kind: service
metadata:
  name: cluster-ip-service
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - name: redis-port
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis
  